### ISSUE TITLE
Draw temperature maps multiple times after each other

### ISSUE THREAD

**Issue by E75** [optimisme/javascript-temperatureMap#1]
I'm doing a hobby project. I load every 2 hours a temperature map with different values (points). I get problems with DrawLow function. Drawing temperature maps multiple times after each other gives rare problems. He remembers his color values. How can I change the color values / polygons, etc. reset so it renders well.

If you reload the page, then it solves the problem. 
But without reloading this bugs appears! and i don't want to reload my page

How can you reset the color values / points / polygons?

What I've tried myself:
Clear the canvas: `ctx0.clearRect(0, 0, can0.width, can0.height);`
Reload the temperatureMap.js: `$('#temperatureMapScript').remove();
    $.getScript("Scripts/temperatureMap.js", function () {
        $('script:last').attr('id', 'temperatureMapScript');`
Reload the canvas:  `$("#canvast1").load(location.href + " #canvast1");`

First time run(the good one)
![firsttimerun](https://cloud.githubusercontent.com/assets/9724772/19182508/d606d77c-8c73-11e6-9cae-dbee9d5657d7.PNG)

After running 10 times the function
![10timerun](https://cloud.githubusercontent.com/assets/9724772/19182514/ddd85728-8c73-11e6-925e-31823e440d98.PNG)

The code i'm using is:

```
var can0 = document.getElementById("canvast1"); // Get the canvas object
```

```
 var ctx0 = can0.getContext("2d");           // Get the canvas context
    var drw0 = new TemperatureMap(ctx0);        // Create the object 
    ctx0.clearRect(0, 0, can0.width, can0.height); //Clear the canvas!
dataSet.d.forEach(function(dataSet) {
        listPoints.push(dataSet);
    });
  drw0.setPoints(listPoints, 500, 500);
    drw0.drawLow(5, 8, true, function () { // 5 = Number of closer influent points
        // 8 = Quality parameter [2, 32]
        //false = clean polygon outside
    drw0.drawPoints();    
    });
```

Can you help me?

**Comment by optimisme** [comment]
Hi,

I amb aware of the problem, I have been thinking on changing the drawing
routine and simplify it (maybe using workers to make it faster)

How would like you to use it? I Will look at the source on the next weekend

**Comment by E75** [comment]
@optimisme Thanks man for your effort and time. Great support:D

I'm using it for my home. I have in my house temperature sensors (Raspberry Pi). I've drawn a blank grid and have your nice javascript layered over it. I just want through an x, y and value transition temperature show in a square area. And then I want to see how many degrees difference is after one week.

To draw a square, I've given standard 4 points with x and y. (canvas max/min x.y coordinates). Then I draw the actual measurement values in this square.

I only came to few bugs, including:
If you have four points and are going to draw a 5th point (Points with 4 corner points and a centre point), it does not render the map!

The feature that I built myself, I do not show the four points. Maybe you can also add them to the next version.  

```

 pointList.Add(new PointObject { value = Math.Round(Value, 2), x = x, y = y, draw = true });

if (pnt.draw) { //pnt.draw is boolean) // TemperatureMap.prototype.drawPoints = function implemented
            ctx.fillStyle = 'rgb(0, 0, 0)';
                ctx.fillText((pnt.value), pnt.x, pnt.y);
            }

```

Day temperature:
![firsttimerun](https://cloud.githubusercontent.com/assets/9724772/19183912/d99779ee-8c7a-11e6-9a89-a74c5fe08d01.PNG)
Night temperature:
![10timerun](https://cloud.githubusercontent.com/assets/9724772/19184142/06bc34a4-8c7c-11e6-9315-84ef2d765a2a.PNG)

This image has officially 10 points (4 of which are made invisible). Maybe you can build a feature where you can draw four corners, and it can fill the real items with values.

Note, for the calculation of the four end points, I use the following C # code:
Gets the nearest point in the listPoint list and i'm giving with another method the value to nearest corner.

```
  private static PointObject NearestPoint(List<PointObject> f1, PointObject pt1)
        {
            var nearPoint = f1.Select(n => new { n, distance = Math.Sqrt(Math.Pow(n.x - pt1.x, 2) + Math.Pow(n.y - pt1.y, 2)) }).OrderBy(p => p.distance).First().n;

            //nearIndex = f1.IndexOf(nearPoint);
            return nearPoint;
        }
```

Features which useful for next versions (Of course, if you have time and nothing to do:D):
- dynamically changing color temperature. Method to choose the color min,max, and level. Now i'm changing in your script file. But this is easy to realize.
- Rendering faster 
- Generating corner values automatic with nearest point.
- Point drawing(visible/invisible)
- Points with information (x,y,value, sensorName, sensorType, sensorNumber) etc.
  (Maybe in the future, when you click on a point, then you can get the values/information about the point. Usefull with almost every temperature map)
- Buffering multiple temperature layers (for switching every 5 minutes of temperature maps etc.)

Note: i'm a beginner JavaScript programmer. But if i have time (i'm studying) than i will help you if you want ;)

**Comment by optimisme** [comment]
Hi

I uploaded a new source forcing to clear the canvas on each low drawing, I
don't understand why your source is not clearing the canvas properly.

Tell me if this fixed your problem

**Comment by E75** [comment]
@optimisme: Note the bug is there. It doesn't fix the problem :(

![firsttimerun](https://cloud.githubusercontent.com/assets/9724772/19187507/1d3df22a-8c8c-11e6-86a7-9fd87d348936.PNG)

Update: i'm using Microsoft Edge browser (maybe chrome or firefox cleans good?)
which browser are you using?

**Comment by E75** [comment]
@optimisme 
Update 2:

I think i found the problem. Every time when i select between day and night points, some points of night are visible in day and vice versa (new bug?). The points and the color(gradient) values are stored locally or something. Javascript library remembers the old color/gradient values. Maybe you can fix it by first clear all values to zero(null) and then fill with the new points. 

![firsttimerun](https://cloud.githubusercontent.com/assets/9724772/19187683/34735d3a-8c8d-11e6-97c8-50dc18977a08.PNG)
Note: Temperature map night loaded (value is day value :))

**Comment by E75** [comment]
@optimisme have you looked at it?

**Comment by E75** [comment]
@optimisme i have done several things, but could not solve it. Had you time to look at it maybe?

**Comment by optimisme** [comment]
Sorry, I have been very bussy last month. I don't know if I will have time.
Have you tried deleting the object and creating a new one at every repaint?

**Comment by E75** [comment]
@optimisme 

I fixed the issue. Maybe you can update when you have the time

The drawlow method must include this lines, because the canvas element remembers the previous state!

```
ctx.width += 0;   //<=== Resizing the canvas will cause the canvas to get cleared.
ctx.beginPath(); 
ctx.fillStyle = "#191919"; //<=== must be filled white for properly render
ctx.closePath(); //<== must be closed
```

```
TemperatureMap.prototype.drawLow = function (limit, res, clean, callback) {

    var self = this,
        ctx = this.ctx,
        dbl = 2 * res,
        col = [],
        cnt = 0,
        x = 0,
        y = 0,
        val = 0.0,
        str = '',
        xBeg = self.limits.xMin,
        yBeg = self.limits.yMin,
        xEnd = self.limits.xMax,
        yEnd = self.limits.yMax,
        lim = limit > self.points.length ? self.points.length : limit + 1,
        gradient;

    ctx.clearRect(0, 0, this.size.width, this.size.height);
    ctx.width += 0;   //<=== Resizing the canvas will cause the canvas to get cleared.

    // Draw aproximation
    for (x = xBeg; x < xEnd; x = x + res) {
        for (y = yBeg; y < yEnd; y = y + res) {
            val = self.getPointValue(lim, { x: x, y: y });
            if (val !== -255) {
                ctx.beginPath();  //<== beginpath
                col = self.getColor(false, val);
                str = 'rgba(' + col[0] + ', ' + col[1] + ', ' + col[2] + ', ';
                gradient = ctx.createRadialGradient(x, y, 1, x, y, res);
                gradient.addColorStop(0, str + '0.5)');
                gradient.addColorStop(1, str + '0)');
                ctx.fillStyle = "#191919"; //<=== must be filled white for properly render
                ctx.fillStyle = gradient;
                ctx.fillRect(x - res, y - res, dbl, dbl);
                ctx.fill();
                ctx.closePath(); //<== must be closed
            }
        }
    }
```

**Comment by optimisme** [comment]
Hi,

I updated the source with your lines, thank you very much.
